loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  auth_enabled: false
singleBinary:
  replicas: 1
monitoring:
  dashboards:
    enabled: false
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false

