agent:
  configMap:
    content: |-
        discovery.kubernetes "rnb" { 
          role = "pod"

          selectors {
            role = "pod"
            label = "name=rnb"
          }
        }

        discovery.kubernetes "postgres" { 
          role = "pod"

          selectors {
            role = "pod"
            label = "k8-app=postgres"
          }
        }

        loki.source.kubernetes "rnb" {
          targets = discovery.kubernetes.rnb.targets
          forward_to = [loki.write.default.receiver]
        }

        loki.source.kubernetes "postgres" {
          targets = discovery.kubernetes.postgres.targets
          forward_to = [loki.write.default.receiver]
        }

        loki.write "default" {
          endpoint { 
            url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push" 
          }
        }
