agent:
  configMap:
    content: |-
        discovery.kubernetes "pods" { 
          role = "pod"

          selectors {
            role = "pod"
            label = "name=rnb"
          }

          namespaces {
            names = ["default"]
          }
        }

        loki.source.kubernetes "pods" {
          targets = discovery.kubernetes.pods.targets
          forward_to = [loki.write.default.receiver]
        }

        loki.write "default" {
          endpoint { 
            url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push" 
          }
        }
