agent:
  configMap:
    content: |-
        discovery.kubernetes "k8s" { 
          role = "pod"
        }

        discovery.relabel "k8s" {
          targets = discovery.kubernetes.k8s.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_label_name"]
            target_label  = "job"
            separator     = "/"
          }

          rule {
            source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
            target_label  = "__path__"
            separator     = "/"
            replacement   = "/var/log/pods/*$1/*.log"
          }
        }

        local.file_match "pods" {
          path_targets = discovery.relabel.k8s.output
        }

        loki.source.file "pods" {
          targets = local.file_match.pods.targets
          forward_to = [loki.write.endpoint.receiver]
        }

        loki.write "endpoint" {
          endpoint { 
            url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push" 
          }
        }
